### ISSUE TITLE
Figure out how to integrate API/Backend and HTML

### ISSUE THREAD

**Issue by ryan-bradford** [ryan-bradford/WHAM#2]
Ways possible:

1. Have the web browser directly query the API with a request for "text/html" and display what it is given. This is the more simple way.

2. Have the web browser load some static scripts that query the API for it and do some processing and fancy JS+CSS stuff. I do not know if this is necessary. All the fancy JS+CSS stuff might be able to be built into the API/Backend.

**Comment by dajinchu** [comment]
Benefits of option 1 (static generated web pages): probably faster page load, browser functions such as forward and back buttons continue to work.
Benefits of option 2 (single page application): unified JSON api backend, no page reloading, less processing for the server. 
We might end up with a combination with both but I think for now it's faster development-wise to stick with option 1 though, because it's simpler for rapid prototyping

**Comment by ryan-bradford** [comment]
I think I agree with that. Doing just the static HTML is going to be much easier to get it up and running.
